# Generated by Django 4.0.4 on 2022-04-26 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('betsoni', models.IntegerField()),
                ('til', models.CharField(max_length=10)),
                ('about', models.TextField()),
            ],
        ),
    ]
