# Generated by Django 4.0.4 on 2022-04-30 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Uquvchi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=200)),
                ('fam', models.CharField(max_length=200)),
                ('otasi', models.CharField(max_length=200)),
                ('yoshi', models.IntegerField()),
                ('sinfi', models.IntegerField()),
            ],
        ),
    ]
